{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.support.ui import Select\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "import psycopg2\n",
    "import sys\n",
    "import socket\n",
    "import datetime\n",
    "\n",
    "def second_page(sd):\n",
    "    driver.find_element_by_xpath(u\"(//input[@value='詳細資料'])[\" + str(sd) + \"]\").click()\n",
    "\n",
    "    time.sleep(6)\n",
    "    now_handle=driver.current_window_handle\n",
    "    all_handles=driver.window_handles\n",
    "    driver.switch_to.window(all_handles[1])\n",
    "    aa=driver.page_source\n",
    "    driver.close()\n",
    "    driver.switch_to_window(all_handles[0])\n",
    "    soup=BeautifulSoup(aa,'html5lib')\n",
    "    \n",
    "    return soup\n",
    "\n",
    "def parser(soup):\n",
    "    compID=soup.find('input',{'name':'Q1V'})['value']\n",
    "    compName=soup.find('input',{'name':'compName'})['value'].replace(' ','')\n",
    "    yyymm=soup.find('input',{'name':'Q2V'})['value']\n",
    "    mamaID=compID[0:4]\n",
    "    timestamp=time.strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "    print(\"id=\" + compID + \"; compName=\" + compName + \"; yyymm=\" + yyymm)\n",
    "\n",
    "    name=[]\n",
    "    name.append('非持有_符合避險_未沖銷_總金額')\n",
    "    name.append('非持有_符合避險_未沖銷_公允價值')\n",
    "    name.append('非持有_符合避險_未沖銷_未實現')\n",
    "    name.append('非持有_符合避險_已沖銷_總金額')\n",
    "    name.append('非持有_符合避險_已沖銷_已實現')\n",
    "    name.append('非持有_不符合避險_未沖銷_總金額')\n",
    "    name.append('非持有_不符合避險_未沖銷_公允價值')\n",
    "    name.append('非持有_不符合避險_未沖銷_未實現')\n",
    "    name.append('非持有_不符合避險_已沖銷_總金額')\n",
    "    name.append('非持有_不符合避險_已沖銷_已實現')\n",
    "\n",
    "    td=[]\n",
    "    for i in range(0,10):\n",
    "        td.append(0)\n",
    "\n",
    "    for tb in soup.findAll('table',{'class':'hasBorder'}):\n",
    "        a1=tb.findAll('tr',{'class':False})[0].findAll('td',{'class':'tblHead'})[0].text\n",
    "        #print(first_head)\n",
    "        if a1=='非持有供交易':\n",
    "            a2=tb.findAll('tr',{'class':False})[0].findAll('td',{'class':'tblHead'})[1].text\n",
    "            if a2=='不符避險會計':\n",
    "                td[5]=tb.findAll('tr',{'class':False})[2].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "                td[6]=tb.findAll('tr',{'class':False})[3].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "                td[7]=tb.findAll('tr',{'class':False})[4].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "                td[8]=tb.findAll('tr',{'class':False})[5].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "                td[9]=tb.findAll('tr',{'class':False})[6].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "            elif a2=='符合避險會計':\n",
    "                td[0]=tb.findAll('tr',{'class':False})[2].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "                td[1]=tb.findAll('tr',{'class':False})[3].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "                td[2]=tb.findAll('tr',{'class':False})[4].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "                td[3]=tb.findAll('tr',{'class':False})[5].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "                td[4]=tb.findAll('tr',{'class':False})[6].findAll('td',{'style':True})[-4].text.replace(',','').replace(' ','')\n",
    "    isum=0\n",
    "    for i in range(0,10):\n",
    "        isum=isum+ int(td[i])\n",
    "       \n",
    "    if isum!=0:\n",
    "        for i in range(0,10):\n",
    "            cur.execute(\"insert into 遠期契約申報資料(id,mama_id,name,yyymm,item,value,insert_dt) values(\" + compID + \",\" + mamaID + \",'\" + compName + \"',\" + yyymm + \",'\" + name[i] + \"',\" + str(td[i]) + \",'\" + timestamp + \"')\")   \n",
    "            conn.commit()\n",
    "\n",
    "def isExist(soup):\n",
    "    compID=soup.find('input',{'name':'Q1V'})['value']\n",
    "    yyymm=soup.find('input',{'name':'Q2V'})['value']\n",
    "    mamaID=compID[0:4]\n",
    "    \n",
    "   # cur.execute(\"select count(id) from 遠期契約申報資料 where id='\" + mamaID + \"' and yyymm='\" + yyymm + \"';\")   \n",
    "  #  arr=cur.fetchall()\n",
    "   # conn.commit()\n",
    "  #  return str(arr[0][0])\n",
    "    return '0'\n",
    "\n",
    "def start_level(sp):\n",
    "    if isExist(sp)=='0': \n",
    "        all_lists=0\n",
    "        for i in sp.findAll('input',{'type':'button','value':'詳細資料'}):\n",
    "            all_lists=all_lists+1\n",
    "\n",
    "        isSuccess=False\n",
    "        iStart=1\n",
    "        recursive=0\n",
    "        while(isSuccess==False):\n",
    "            try:\n",
    "                for i in range(iStart,all_lists+1):\n",
    "                    soup=second_page(i)\n",
    "                    print(\"second_page(soup)\"+soup)\n",
    "                    print(\"\\n\")\n",
    "               #     parser(soup)\n",
    "\n",
    "                isSuccess=True\n",
    "                print('Mission complete!!!')\n",
    "            except:\n",
    "                if recursive<3:\n",
    "                    iStart=i\n",
    "                    recursive=recursive+1\n",
    "                    print('stop at ' + str(iStart) + ', and recursive times = ' + str(recursive))\n",
    "                else:\n",
    "                    iStart=i+1\n",
    "                    recursive=0\n",
    "                \n",
    "        driver.close()\n",
    "    else:\n",
    "        print('Already exists!!!')\n",
    "        driver.close()\n",
    "\n",
    "        \n",
    "def trigger(myID, myYYY, myMM):\n",
    " #   if socket.gethostbyname(socket.gethostname())=='172.27.110.104':\t#Jack's pc\n",
    "   #     ipath='D:\\\\Python36\\\\phantomjs.exe'\n",
    "  #  elif socket.gethostbyname(socket.gethostname())=='172.27.111.34': \t#Jay's pc\n",
    "   #     ipath='C:\\\\Program Files\\\\Python35\\\\Scripts\\\\phantomjs.exe'\n",
    "   # elif socket.gethostbyname(socket.gethostname())=='172.27.110.105': \t#Allen's pc\n",
    "   #     ipath='D:\\\\Python\\\\Python35\\\\phantomjs.exe'\n",
    "    ipath='D:\\\\financial_data_web_scrawer\\\\phantomjs.exe'\n",
    "\t\t\n",
    "    global driver\n",
    "    driver=webdriver.PhantomJS(ipath,service_args=['--ignore-ssl-errors=true','--ssl-protocol=TLSv1'])\n",
    "\n",
    "   # driver=webdriver.Firefox()\n",
    "    driver.get(\"http://mops.twse.com.tw/mops/web/t15sf\")\n",
    "    print(\"myID:\"+myID)\n",
    "    print(\"\\n\")\n",
    "    print(\"year:\"+myYYY)\n",
    "    print(\"\\n\")\n",
    "    print(\"month:\"+myMM)\n",
    "    print(\"\\n\")\n",
    "    driver.find_element_by_id('co_id').send_keys(myID)\n",
    "    driver.find_element_by_id('year').send_keys(myYYY)\n",
    "    driver.find_element_by_id('month').send_keys(int(myMM))\n",
    "    #Select(driver.find_element_by_id('month')).select_by_visible_text(int(myMM))\n",
    "    driver.find_element_by_css_selector('div.search > input[type=\\\"button\\\"]').click()\n",
    "    time.sleep(6)\n",
    "    soup=BeautifulSoup(driver.page_source,'html5lib')\n",
    "   # print(soup)\n",
    "    is_no_data=False\n",
    "    for center in soup.findAll('center'):\n",
    "        if center.text=='該公司並未申報本項資料':\n",
    "            is_no_data=True\n",
    "    \n",
    "    if is_no_data:\n",
    "        print('該公司並未申報本項資料')\n",
    "    else:\n",
    "        start_level(soup)\t\t\n",
    "\t\t\n",
    "def get_all_code(strName):\n",
    "    host_str=connection_info()\n",
    "    conn1=psycopg2.connect(host=host_str,port='5432',database='equity',user='quant',password='quant')\n",
    "    cur1=conn1.cursor()\n",
    "    cur1.execute(\"select id from \" + strName + \" order by id\")   \n",
    "    arr=cur1.fetchall()\n",
    "    cur1.close()\n",
    "    conn1.close()\n",
    "    return arr\n",
    "\t\n",
    "#add id and date to trrigger \n",
    "def iteration(arr, start_from=0, end_to=9999):\n",
    "    lastmon=datetime.datetime.today()-datetime.timedelta(days=100)\n",
    "    myYYY=str(int(lastmon.strftime(\"%Y\"))-1911)\n",
    "    myMM=lastmon.strftime(\"%m\")\n",
    "    myID=''\n",
    "    \n",
    "    for i in range(0,len(arr)):\n",
    "        myID='2353'\n",
    "        if int(myID)>=start_from and int(myID)<=end_to:\n",
    "            trigger(myID, myYYY, myMM)\n",
    "# connect to local db\n",
    "def connection_info():\n",
    "    #ipstr=socket.gethostbyname(socket.gethostname())\n",
    "    #if ipstr=='172.27.110.104':\n",
    "    #    conn_info='localhost'\n",
    "    #else:\n",
    "    #    conn_info='172.27.110.104'  #this is Jack's pc\n",
    "    conn_info='localhost'\n",
    "    return conn_info\n",
    "lastmon=datetime.datetime.today()-datetime.timedelta(days=100)\n",
    "print(\"lastmon\"+str(lastmon))\n",
    "myYYY=str(int(lastmon.strftime(\"%Y\"))-1911)\n",
    "myMM=lastmon.strftime(\"%m\")\n",
    "myID=''\n",
    "\n",
    "#host_str=connection_info()\n",
    "#conn=psycopg2.connect(host=host_str,port='5432',database='postgres',user='quant',password='quant')\n",
    "#cur=conn.cursor()\n",
    "\n",
    "arr=['2353','2317']\n",
    "iteration(arr)  \t# for debug purpose\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
